services:
  comuni-ita-api:
    container_name: comuni-ita-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data # Mount the data directory for easy updates
    restart: unless-stopped
